#!/bin/sh
#
# This script is intended to set up your debian-based Linux distributions with web development solution.
# The script takes further steps by install Apache + PHP + MySQL/MariaDB.
#
# Copyright (C) 2021 Malxserver Version: 1.0
#
# GNU GENERAL PUBLIC LICENSE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

## ===================================================================
# Show program banner
# ===================================================================

banner() {

cat << "EOF"
  __  __           _
 |  \/  |         | |
 | \  / |   __ _  | | __  __  ___    ___   _ __  __   __   ___   _ __
 | |\/| |  / _` | | | \ \/ / / __|  / _ \ | '__| \ \ / /  / _ \ | '__|
 | |  | | | (_| | | |  >  <  \__ \ |  __/ | |     \ V /  |  __/ | |
 |_|  |_|  \__,_| |_| /_/\_\ |___/  \___| |_|      \_/    \___| |_|

    Malxserver Version: 1.0
  -------------------------------------------------------
EOF

}

# ===================================================================
# Colors for terminal
# ===================================================================

   BLUE='\033[1;94m'
   GREEN='\033[1;92m'
   RED='\033[1;91m'
   PURPLE='\033[1;35m'
   ENDC='\033[1;00m'

   # ===================================================================
# Check if the program run as a root
# ===================================================================

check_root(){

# Make sure only root can run this script
        if [ $(id -u) -ne 0 ]; then
          echo "\n$RED[!] This script must be run as root$ENDC\n" >&2
          exit 1
        fi

}

# ===================================================================
# Start, stop, restart, status of Malxserver
# ===================================================================
# Initialization setup
case "$1" in
    start)
     banner
     check_root
     systemctl start apache2
     systemctl start mariadb
     

    ;;
    stop)
    banner
    check_root

    ;;
    restart)
        $0 stop
        $0 start
    ;;
    status)
    banner
    check_root
    ;;
    *)
      echo "\n$RED[!] Usage: start Malxserver with {start|stop|restart|status} $ENDC\n"
    exit 1
    ;;
esac

exit 0

# End of program
# ===================================================================
